let phoneCountryCodeData: [CountryCode] = [
    CountryCode(name: "United States", code: "US", dialCode: "+1"),
    CountryCode(name: "Canada", code: "CA", dialCode: "+1"),
    CountryCode(name: "United Kingdom", code: "GB", dialCode: "+44"),
    CountryCode(name: "Germany", code: "DE", dialCode: "+49"),
    CountryCode(name: "France", code: "FR", dialCode: "+33"),
    CountryCode(name: "Italy", code: "IT", dialCode: "+39"),
    CountryCode(name: "Spain", code: "ES", dialCode: "+34"),
    CountryCode(name: "Australia", code: "AU", dialCode: "+61"),
    CountryCode(name: "India", code: "IN", dialCode: "+91"),
    CountryCode(name: "China", code: "CN", dialCode: "+86"),
    CountryCode(name: "Japan", code: "JP", dialCode: "+81"),
    CountryCode(name: "South Korea", code: "KR", dialCode: "+82"),
    CountryCode(name: "Brazil", code: "BR", dialCode: "+55"),
    CountryCode(name: "Mexico", code: "MX", dialCode: "+52"),
    CountryCode(name: "Russia", code: "RU", dialCode: "+7"),
    CountryCode(name: "South Africa", code: "ZA", dialCode: "+27"),
    CountryCode(name: "Nigeria", code: "NG", dialCode: "+234"),
    CountryCode(name: "Saudi Arabia", code: "SA", dialCode: "+966"),
    CountryCode(name: "Turkey", code: "TR", dialCode: "+90"),
    CountryCode(name: "Indonesia", code: "ID", dialCode: "+62"),
    CountryCode(name: "Pakistan", code: "PK", dialCode: "+92"),
    CountryCode(name: "Bangladesh", code: "BD", dialCode: "+880"),
    CountryCode(name: "Egypt", code: "EG", dialCode: "+20"),
    CountryCode(name: "United Arab Emirates", code: "AE", dialCode: "+971")
]
